name: Deploy to Github Pages
on:
  workflow_dispatch:
  push:
    branches:
      - cssInJS
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: |
          npm i
          npm run build
          cd build
          git init
          # type configurations: your user.email and user.name followed lines 
          git config --global user.email emily@whitings.org
          git config --global user.name EmilyWhiting
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/emilyswhiting/kid-app.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
